[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'

[tool.poetry]
name = "textworker"
version = "1.6dev1"
description = "It's just a text editor"
authors = ["lebao3105 <bao12345yocoo@gmail.com>"]
license = "GPL_V3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
libtextworker = {path = "libtextworker"}
Pillow = "^9.5.0"
wxPython = "^4.2.0"
cairosvg = {version = "^2.7.0", optional = true}
markdown2 = "^2.4.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
