[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "texteditor"
version = "1.4.1"
requires-python = ">=3.8"
description = "A Tkinter text editor."
readme = "README.md"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Programming Language :: Python",
    "Topic :: Text Editors",
]
dependencies = [
	"configparser",
	"sv_ttk",
    "packaging",
	"pygubu",
	"darkdetect"
]

[tool.setuptools]
package-dir = {"texteditor" = "texteditor"}

[project.gui-scripts]
texteditor = "texteditor:start_app"
