[build-system]
requires = ["configparser", "pillow", "setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "texteditor"
version = "1.0"
dependencies = [
	"configparser",
	"pillow",
	"setuptools"
]
description = "A simple, runnable text editor."

[tool.setuptools.packages.find]
where = ["src", "data"]

