name: Build Debian package (.deb file in ..)

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the repository
        uses: actions/checkout@v3
  
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      # Install required packages
      - name: Install build tools
        run: |
          sudo apt update && sudo apt install devscripts python3-virtualenv python3-tk
          

      # Build
      - name: Build package
        run: |
          debuild -us -uc -b
          
      - name: Install (test)
        run: |
          sudo dpkg -i ../texteditor*.deb
