name: Build releases (deb)

on:
  # release:
  #   types: [published]

  workflow_dispatch:
  workflow_call:

jobs:

  time_to_run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyver: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pyver }}
      
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y universe
          sudo apt update
          sudo apt install -y libgtk-3-dev libsdl2-dev dh-virtualenv devscripts
          pip3 install attrdict3

      - name: Build wheels
        run: debuild -b -us -uc

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Textworker_wxWheel
          path: texteditor/dist/