name: Make exe

on:
  workflow_dispatch:

jobs:
  build:
    # We will run this on Windows
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11-dev"]
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
    
      - name: Install dependencies
        run: pip install configparser py2exe
      
      # We must run the script on /texteditor - otherwise the build won't work
      - name: Copy files
        run: |
          xcopy makerelease\setupwin.py texteditor\
          xcopy makerelease\files.py texteditor\
      
      - name: Start building
        run: python setupwin.py py2exe
        working-directory: texteditor
