name: Build releases (wheel) (wx version)

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+[a][b][d]+[0-9]+.[0-9]"
      - "v[0-9]+.[0-9]"
  workflow_dispatch:

jobs:

  time_to_run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Clone the source code
        run: |
          git clone https://github.com/lebao3105/texteditor.git -b wip/wx
      
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Fetch submodules
        run: |
          git switch wip/wx
          git submodule update --init --recursive
        working-directory: texteditor
      
      - name: Install dependencies
        run: |
          sudo add-apt-repository universe -y
          sudo apt update
          sudo apt install libgtk-3-dev libsdl2-dev -y
          pip3 install attrdict3 requests poetry
          pip3 install wxPython
        working-directory: texteditor
      
      - name: Build wheels
        run: |
          python3 -m poetry build
        working-directory: texteditor

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TextworkerWheel
          path: texteditor/dist/
