name: Build releases (wheel)

on:
  # release:
  #   types: [published]

  workflow_dispatch:
  workflow_call:

jobs:

  time_to_run:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y universe
          sudo apt update
          sudo apt install -y libgtk-3-dev libsdl2-dev curl imagemagick
          curl -L -o wxFB.deb https://github.com/wxFormBuilder/wxFormBuilder/releases/download/v4.2.1/wxformbuilder_4.2.1_ubuntu-22.04_amd64.deb
          sudo dpkg -i wxFB.deb
          pip3 install attrdict3 requests
          pip3 install wxpython build wheel

      - name: Make a wheel
        run: |
          make genui
          make all

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Textworker_wxWheel
          path: texteditor/dist/