name: Build releases (wheel) (Tk version)

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+[a][b][d]+[0-9]+.[0-9]"
      - "v[0-9]+.[0-9]"
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Fetch submodules
        run: |
          git switch main
          git submodule update --init --recursive

      - name: Install dependencies
        run: |
          git switch main
          sudo apt install python3-tk -y
          pip3 install build wheel
          pip3 install -r requirements.txt
      
      - name: Build
        run: |
          python3 -m build
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TextworkerWheel
          path: dist/
