name: Build releases (wheel) (wx version)

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Fetch the latest commit
        run: |
          git submodule update --remote
      
      - name: Install dependencies
        run: |
          sudo add-apt-repository universe -y
          sudo apt update
          sudo apt install libgtk-3-dev libsdl2-dev -y
          pip3 install attrdict3 requests build wheel
          pip3 install git+https://github.com/wxWidgets/Phoenix
          pip3 install -r requirements.txt
        working-directory: textworker
      
      - name: Build
        run: |
          python3 -m build
        working-directory: textworker
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TextworkerWheel
          path: textworker/dist/
