name: Build releases (wheel) (wx version)

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          sudo add-apt-repository universe -y
          sudo apt update
          sudo apt install gettext meson ninja-build -y
          sudo apt install libsdl2-dev libgtk3-dev -y
          pip3 install attrdict3 requests build wheel
          pip3 install -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.0-cp310-cp310-linux_x86_64.whl
          pip3 install -r requirements.txt
      
      - name: Generate translations
        run: |
          meson build
          ninja -C build me.lebao3105.textworker-pot
          ninja -C build me.lebao3105.textworker-update-po
          ninja -C build me.lebao3105.textworker-gmo
          cp -r build/po/* po/

      - name: Build
        run: |
          python3 -m build
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: TextworkerWheel
          path: dist/
