name: Build releases (wheel) (Tk version)

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the source code
        run: |
          git clone https://github.com/lebao3105/texteditor.git
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Fetch submodules
        run: |
          git submodule update --init --recursive
        working-directory: texteditor

      - name: Install dependencies
        run: |
          sudo apt install python3-tk -y
          pip3 install poetry wheel
        working-directory: texteditor
      
      - name: Build
        run: |
          python3 -m poetry build
        working-directory: texteditor
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Textworker_tkWheel
          path: texteditor/dist/
